version: '3.9'

services:
  oi4-oec-registry:
    image: oi4/oi4-registry:1.1.0-preview.1
    container_name: oi4-oec-service-demo
    restart: on-failure
    volumes:
      - "/my/local/path/to/oi4-oec-registry-1.1.0-preview.1/mqtt:/etc/oi4/mqtt"
      - "/my/local/path/to/oi4-oec-registry-1.1.0-preview.1/certs:/etc/oi4/certs"
      - "/my/local/path/to/oi4-oec-registry-1.1.0-preview.1/secrets:/run/secrets"
      - "/my/local/path/to/oi4-oec-registry-1.1.0-preview.1/config:/etc/oi4/config"
    ports:
      - "5798:5798"
      - "5799:5799"
    environment:
      - TZ=Europe/Berlin
      - OI4_EDGE_EVENT_LEVEL=warning
      - OI4_EDGE_LOG_LEVEL=debug
    labels:
      com.centurylinklabs.watchtower.enable: "true"
networks:
  oi4:
    driver: bridge
    name: oi4
